### PR TITLE
Adds schema version 2 that does not require node_modules

### PR DESCRIPTION
**Pull request by dianabarsan**
#31

### CODE REVIEW

**Comment by dianabarsan** [comment]
Hey @garethbowen . What do you think about schema 2? I think the validate function can be improved too, but I'm really not sure about the approach. Thanks!

**Review by garethbowen — APPROVED** [review]
Looks good to me. Which validate function were you thinking about?

**Comment by dianabarsan** [comment]
The `validate_doc_update` functions that just duplicate the list of required keys. es5 is such a pain to write code with. :(

**Comment by garethbowen** [comment]
Definitely. I don't think it's worth the additional effort.

**Pull request merged**
